[project]
name = "indelMaP"
version = "1.0.0"
description = "Indel-Aware Maximum Parsimony"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ete3>=3.1.3",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
]
